landing page typo fixed
Haywayaheadshot/abu-the-portfolio pull request #25
Opened 2023-04-12 16:11 UTC by Pragyan14

Could you please provide me with a brief overview of any additional changes you would like to make, such as hover effects, the landing page image, font, and the landing page sentence?

2023-04-13 02:23 UTC, Haywayaheadshot commented
@Pragyan14 Thank you for working on this project. Could you please rebase your pull request?

2023-04-13 03:31 UTC, Pragyan14 commented
I recently started contributing, and I'm still learning how to use github. Could you kindly explain what rebase is and how to use it?

2023-04-13 14:20 UTC, Haywayaheadshot commented
That's okay @Pragyan14. I believe we are all here to learn from each other. The concept of rebasing is quite simple. When you submit a pull request to a Git repository, it's possible that the target branch (usually main or master) has changed since you last synced your branch with it. This can lead to conflicts when your changes are merged into the target branch.

Rebasing a pull request is the process of updating your branch with the latest changes from the target branch so that your changes can be applied cleanly on top of it. This involves essentially moving the base of your branch to a more recent commit on the target branch.

To do this, you would first fetch the latest changes from the target branch into your local repository, and then use the git rebase command to rebase your branch on top of the updated target branch. This will apply your changes on top of the latest changes from the target branch, resolving any conflicts that arise in the process.

Rebasing a pull request can be useful for a number of reasons, such as ensuring that your changes are based on the latest code in the target branch, and reducing the likelihood of conflicts when your changes are merged. It's a common practice in Git workflows and is especially important when working collaboratively on a project.

2023-04-13 14:37 UTC, Haywayaheadshot requested changes
## Hi @Pragyan14 ✋

Good job so far!

## Highlights!
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️

Hello ✋, Thank you so much for working on this project. Your input and time are appreciated. 🤝 . But there are some issues that you still need to work!

# Status: Required Changes ♻️⛔️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-13 14:37 UTC, Haywayaheadshot commented on .eslintrc.json
> +      "indent":"off",
I do not think it will be a good idea to put off indentation as it helps enforce consistent indentation in the code, to improve readability and maintainability.

It's worth noting that disabling the `indent` rule can potentially lead to code that is more difficult to read and maintain over time.

2023-04-13 14:37 UTC, Haywayaheadshot commented on src/styles/about.css
> +}
When you rebase your PR, you'll realize the link tags have been styled when hovered upon. I believe you'll find that we don't need this additional one. Please delete it.

2023-04-14 16:11 UTC, Haywayaheadshot commented on src/pages/Home.js
> +        try not to hesitate to contact me.
Kindly replace this paragraph with the one below;

`
Welcome to my portfolio!

I am excited to offer my skills to help you create your dream product, feature, or website. Please take a moment to browse through my previous work and experience. If you find yourself impressed with what you see, don't hesitate to reach out to me with your project. I'm looking forward to working with you!
`

2023-04-14 17:21 UTC, Haywayaheadshot approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello  @Pragyan14 , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- [x] No Linter Errors

Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-04-14 17:21 UTC, merged